<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>engine-free-rpg</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>enginefreerpg</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'ExportRelease'">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <_EnableConsumingManagedCodeFromNativeHosting>true</_EnableConsumingManagedCodeFromNativeHosting>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\Game.Godot\**\*.cs" Exclude="src\Game.Godot\**\obj\**\*.cs;src\Game.Godot\**\bin\**\*.cs;src\Game.Godot\**\.godot\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src\Game.Content\Game.Content.csproj" />
    <ProjectReference Include="src\Game.Application\Game.Application.csproj" />
    <ProjectReference Include="src\Game.Expressions\Game.Expressions.csproj" />
    <ProjectReference Include="src\Game.Presentation\Game.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'ExportRelease'">
    <TrimmerRootAssembly Include="GodotSharp" />
    <TrimmerRootAssembly Include="$(AssemblyName)" />
    <TrimmerRootAssembly Include="Game.Core" />
    <TrimmerRootAssembly Include="Game.Content" />
    <TrimmerRootAssembly Include="Game.Application" />
    <TrimmerRootAssembly Include="Game.Expressions" />
    <TrimmerRootAssembly Include="Game.Presentation" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Game.Godot\Map\" />
    <Folder Include="src\Game.Godot\UI\Character\" />
    <Folder Include="src\Game.Godot\UI\GameConfig\" />
    <Folder Include="src\Game.Godot\UI\GameLog\" />
    <Folder Include="src\Game.Godot\UI\HeroInfo\" />
    <Folder Include="src\Game.Godot\UI\Inventory\" />
  </ItemGroup>
</Project>
